/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.90
 * Generated at: 2024-08-15 13:37:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Edit_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1722324252153L));
    _jspx_dependants.put("jar:file:/D:/Eclipse/workspace/bai_tap_jsp_servlet/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/bai_tap_jsp_servlet/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153359882000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("   <head>\r\n");
      out.write("      <meta charset=\"UTF-8\">\r\n");
      out.write("      <title>Insert title here</title>\r\n");
      out.write("      <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\" \r\n");
      out.write("         rel=\"stylesheet\" \r\n");
      out.write("         integrity=\"sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH\"\r\n");
      out.write("         crossorigin=\"anonymous\">\r\n");
      out.write("      <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js\" \r\n");
      out.write("         integrity=\"sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz\" \r\n");
      out.write("         crossorigin=\"anonymous\"></script>\r\n");
      out.write("      <script src=\"https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment.min.js\"></script>\r\n");
      out.write("		<script src=\"https://code.jquery.com/jquery-3.4.1.min.js\"></script>\r\n");
      out.write("   </head>\r\n");
      out.write("   <style>\r\n");
      out.write("		.rq{\r\n");
      out.write("			color: red;\r\n");
      out.write("		}\r\n");
      out.write("	\r\n");
      out.write("   </style>\r\n");
      out.write("   <body>\r\n");
      out.write("   \r\n");
      out.write("   	  ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write("\r\n");
      out.write("   	  \r\n");
      out.write("      <div class=\"container border\" style=\"margin-top:100px; width:800px; border-radius: 10px;\">\r\n");
      out.write("      <center><h3>Update Employyee</h3></center>\r\n");
      out.write("         <form id=\"updateForm\" action=\"EditEmployee\" method=\"post\">\r\n");
      out.write("            <table class=\"table\">\r\n");
      out.write("              <tr>\r\n");
      out.write("	               <td><label for=\"nameEmployee\" class=\"form-label\">EmployeeId</label></td>\r\n");
      out.write("	                  <td>\r\n");
      out.write("	                     <input type=\"text\" class=\"form-control\" id=\"custId\" aria-describedby=\"emailHelp\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${employeeInfo.employeeId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" name=\"Id\" readonly style=\"text-align: center; background-color: #cfd3ce;\">\r\n");
      out.write("	                  	 <span class=\"rq\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${msgEmployeeId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\r\n");
      out.write("	                  </td>\r\n");
      out.write("	               </tr>\r\n");
      out.write("              	\r\n");
      out.write("              </tr>\r\n");
      out.write("               <tr>\r\n");
      out.write("                  <td><label for=\"nameEmployee\" class=\"form-label\">EmployeeName</label></td>\r\n");
      out.write("                  <td>\r\n");
      out.write("                     <input type=\"text\" class=\"form-control\" id=\"nameEmployee\" aria-describedby=\"emailHelp\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${employeeInfo.employeeName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" name=\"nameEmployee\" style=\"text-align: center; background-color: #cfd3ce;\" readonly>\r\n");
      out.write("                  	 <span class=\"rq\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${msgEmployeeName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\r\n");
      out.write("                  </td>\r\n");
      out.write("               </tr>\r\n");
      out.write("               <tr>\r\n");
      out.write("                  <td><label for=\"birthDayEmployee\" class=\"form-label\">EmployeeBirthDate</label></td>\r\n");
      out.write("                  <td>\r\n");
      out.write("                     <input type=\"date\" class=\"form-control\" id=\"birthDayEmployee\" name=\"birthDayEmployee\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${employeeInfo.employeBirthDay}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" required=\"required\">\r\n");
      out.write("                     <span class=\"rq\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${msgErrorBithDate}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\r\n");
      out.write("                  </td>\r\n");
      out.write("                  \r\n");
      out.write("               </tr>\r\n");
      out.write("               <tr>\r\n");
      out.write("                  <td><label for=\"emailEmployee\" class=\"form-label\">Email address</label></td>\r\n");
      out.write("                  <td>\r\n");
      out.write("                     <input type=\"email\" class=\"form-control\" id=\"emailEmployee\" aria-describedby=\"emailHelp\" name=\"emailEmployee\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${employeeInfo.emailEmployee}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" style=\"text-align: center;\">\r\n");
      out.write("                     <div id=\"emailHelp\" class=\"form-text\">We'll never share your email with anyone else.</div>\r\n");
      out.write("                     <span class=\"rq\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${msgEmail}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\r\n");
      out.write("                  </td>\r\n");
      out.write("               </tr>\r\n");
      out.write("               <tr>\r\n");
      out.write("                  <td><label for=\"ageEmployee\" class=\"form-label\">EmployeeAge</label></td>\r\n");
      out.write("                  <td>\r\n");
      out.write("                     <input type=\"number\" class=\"form-control\" id=\"ageEmployee\" aria-describedby=\"emailHelp\" name=\"ageEmployee\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${employeeInfo.employeeAge}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" style=\"text-align: center; background-color: #cfd3ce;\">\r\n");
      out.write("                     <span class=\"rq\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${msgEmployeeAge}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\r\n");
      out.write("                  </td>\r\n");
      out.write("               </tr>\r\n");
      out.write("               <tr>\r\n");
      out.write("                  <td><label for=\"inlineRadio1\" class=\"form-label\">EmployeeGender</label></td>\r\n");
      out.write("                  <td>\r\n");
      out.write("                  	 <div>\r\n");
      out.write("                  	 	<div class=\"form-check form-check-inline\">\r\n");
      out.write("	                        <input class=\"form-check-input\" type=\"radio\" name=\"inlineRadioOptions\" id=\"inlineRadio1\" value=\"male\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${employeeInfo.employeeGender == 'male' ? 'checked' : ''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" style=\"text-align: center;\">\r\n");
      out.write("	                        <label class=\"form-check-label\" for=\"inlineRadio1\">Male</label>\r\n");
      out.write("	                     </div>\r\n");
      out.write("	                     <div class=\"form-check form-check-inline\">\r\n");
      out.write("	                        <input class=\"form-check-input\" type=\"radio\" name=\"inlineRadioOptions\" id=\"inlineRadio2\" value=\"female\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${employeeInfo.employeeGender == 'female' ? 'checked' : ''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" >\r\n");
      out.write("	                        <label class=\"form-check-label\" for=\"inlineRadio2\">Female</label>\r\n");
      out.write("	                     </div>\r\n");
      out.write("	                     <div class=\"form-check form-check-inline\">\r\n");
      out.write("	                        <input class=\"form-check-input\" type=\"radio\" name=\"inlineRadioOptions\" id=\"inlineRadio3\" value=\"orther\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${employeeInfo.employeeGender == 'orther' ? 'checked' : ''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">\r\n");
      out.write("	                        <label class=\"form-check-label\" for=\"inlineRadio3\">Orther</label>\r\n");
      out.write("	                     </div>\r\n");
      out.write("                  	 \r\n");
      out.write("                  	 </div>\r\n");
      out.write("                     \r\n");
      out.write("                     <div>\r\n");
      out.write("                     	<span class=\"rq\"> ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${msgGender}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" </span>\r\n");
      out.write("                     </div>\r\n");
      out.write("                     \r\n");
      out.write("                  </td>\r\n");
      out.write("               </tr>\r\n");
      out.write("               <tr>\r\n");
      out.write("                  <td><label for=\"addressEmployee\" class=\"form-label\">EmployeeAddress</label></td>\r\n");
      out.write("                  <td>\r\n");
      out.write("                     <textarea  class=\"form-control\" id=\"addressEmployee\" aria-describedby=\"emailHelp\" name=\"addressEmployee\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${employeeInfo.employeeAddress}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</textarea>\r\n");
      out.write("                  </td>\r\n");
      out.write("               </tr>\r\n");
      out.write("               <tr>\r\n");
      out.write("                  <td><label for=\"exampleInputEmail1\" class=\"form-label\">Position</label></td>\r\n");
      out.write("                  <td>\r\n");
      out.write("                     <select class=\"form-control\" id=\"selection\" name=\"position\">\r\n");
      out.write("                        <option value=\"employee\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${employeeInfo.position == 'employee' ? 'selected' : ''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">Employee</option>\r\n");
      out.write("                        <option value=\"boss\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${employeeInfo.position == 'boss' ? 'selected' : ''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">Boss</option>\r\n");
      out.write("                     </select>\r\n");
      out.write("                     <span class=\"rq\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${msgPosition}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\r\n");
      out.write("                  </td>\r\n");
      out.write("               </tr>\r\n");
      out.write("               <tr>\r\n");
      out.write("                  <td><label for=\"dateJoiningBirthday\" class=\"form-label\">DateOfJoiningTheCompany</label></td>\r\n");
      out.write("                  <td>\r\n");
      out.write("                     <input type=\"date\" class=\"form-control\" id=\"dateJoiningCompany\" name=\"dateJoiningCompany\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${employeeInfo.employeeDateOfJoiningTheCompany}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" required=\"required\">\r\n");
      out.write("                    <span class=\"rq\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${msgEmployeeDateJoiningCompany}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\r\n");
      out.write("                  </td>\r\n");
      out.write("               </tr>\r\n");
      out.write("            </table>\r\n");
      out.write("            <div class=\"grid\" style=\"padding:20px;\">\r\n");
      out.write("            	<button type=\"submit\" class=\"btn btn-primary\">Update</button>\r\n");
      out.write("            </div>\r\n");
      out.write("         </form>\r\n");
      out.write("      </div>\r\n");
      out.write("   </body>\r\n");
      out.write("   <script>\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write(" $(\"#dateJoiningBirthday\").blur(function(){\r\n");
      out.write("	    const dateValue = new Date($(this).val());\r\n");
      out.write("	    \r\n");
      out.write("	    if (isNaN(dateValue)) {\r\n");
      out.write("	        return '';\r\n");
      out.write("	    }\r\n");
      out.write("	    \r\n");
      out.write("	    const day = String(dateValue.getDate()).padStart(2, '0');\r\n");
      out.write("	    const month = String(dateValue.getMonth() + 1).padStart(2, '0');\r\n");
      out.write("	    const year = dateValue.getFullYear();\r\n");
      out.write("	  \r\n");
      out.write("	    var text = day + \"/\" + month + \"/\" + year;\r\n");
      out.write("	    $(this).attr(\"type\",\"text\");\r\n");
      out.write("	    $(this).val(text);\r\n");
      out.write("});\r\n");
      out.write("	\r\n");
      out.write("/*$(\"#dateJoiningCompany\").blur(function(){\r\n");
      out.write("    const dateValue = new Date($(this).val());\r\n");
      out.write("    \r\n");
      out.write("    if (isNaN(dateValue)) {\r\n");
      out.write("        return '';\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    const day = String(dateValue.getDate()).padStart(2, '0');\r\n");
      out.write("    const month = String(dateValue.getMonth() + 1).padStart(2, '0');\r\n");
      out.write("    const year = dateValue.getFullYear();\r\n");
      out.write("  \r\n");
      out.write("    var text = year + \"-\" + month + \"-\" + day;\r\n");
      out.write("    $(this).attr(\"type\",\"text\");\r\n");
      out.write("    $(this).val(text);\r\n");
      out.write("});\r\n");
      out.write("*/\r\n");
      out.write(" $(\"#birthDayEmployee\").blur(function(){\r\n");
      out.write(" 	\r\n");
      out.write(" 	var date1 = new Date();\r\n");
      out.write(" 	\r\n");
      out.write(" 	var values = $(this).val();\r\n");
      out.write(" 	var yeard = parseInt(values.substr(0, 4));\r\n");
      out.write(" 	console.log(yeard);\r\n");
      out.write(" 	currentYear = date1.getFullYear();\r\n");
      out.write(" 	\r\n");
      out.write(" 	age = currentYear - yeard;\r\n");
      out.write(" 	$(\"#ageEmployee\").val(age);\r\n");
      out.write(" });\r\n");
      out.write(" \r\n");
      out.write("/* $(\"#updateForm\").submit(function(){\r\n");
      out.write(" 	\r\n");
      out.write(" 	$(\"#ageEmployee\").disabled = false;	\r\n");
      out.write(" 	\r\n");
      out.write(" 	\r\n");
      out.write(" })*/\r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("     \r\n");
      out.write(" $(\"form\").on('submit', function(){\r\n");
      out.write("	 //$(\"#ageEmployee\").disabled = false;	\r\n");
      out.write("	  var isConfirmed = confirm(\"Bạn chắc muốn thay đổi?\");\r\n");
      out.write("	  \r\n");
      out.write("	  if (!isConfirmed){\r\n");
      out.write("		  event.preventDefault();\r\n");
      out.write("	  }\r\n");
      out.write(" })\r\n");
      out.write(" \r\n");
      out.write("      \r\n");
      out.write("// Lấy ngày hiện tại\r\n");
      out.write("    var today = new Date().toISOString().split('T')[0];\r\n");
      out.write("    // Đặt giá trị max của input là ngày hiện tại\r\n");
      out.write("    document.getElementById('dateJoiningCompany').setAttribute('max', today);\r\n");
      out.write("    // Thiết lập giá trị max là ngày hiện tại\r\n");
      out.write("    document.getElementById('dateJoiningCompany').max = new Date().toISOString().split(\"T\")[0];      \r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("   </script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
